@baseUrl = http://localhost:3000/api

### 1. Login (Admin) - Para pegar o Token
# Faz o login com o usuário admin padrão criado automaticamente
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###
@authToken = {{login.response.body.access_token}}

### 2. Criar Novo Usuário
# Cria um usuário comum
# @name createUser
POST {{baseUrl}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Novo Admin",
  "email": "admin@climatec.com.br",
  "password": "admin123"
}

###
@userId = {{createUser.response.body._id}}

### 3. Listar Todos os Usuários
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### 4. Buscar Usuário por ID
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

### 5. Atualizar Usuário
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Admin Climatec",
  "email": "climatec@email.com"
}

### 6. Excluir Usuário
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

### ENVIAR DADOS DE CLIMA (via REST Client)
POST http://localhost:3000/api/weather/logs
Content-Type: application/json
Authorization: Bearer SEU_TOKEN_AQUI

{
  "data": {
    "temperature": 25.3,
    "humidity": 62,
    "wind_speed": 10.5,
    "weather_code": 3,
    "weather_condition": "Nublado"
  },
  "location": {
    "city": "Mauá",
    "state": "São Paulo",
    "country": "Brasil",
    "latitude": -23.64683,
    "longitude": -46.4551
  },
  "processed_by": "rest-client-test",
   "timestamp": "2024-07-29T10:00:00Z"

}
